steps:
  # Dockerイメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/bgr4-api-db:latest"
      - "-f"
      - "bgr4-api/Dockerfile.db"
      - "."

  # Google Container Registryへのプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/bgr4-api-db:latest"

# 生成されるイメージの指定
images:
  - "gcr.io/$PROJECT_ID/bgr4-api-db:latest"

# タイムアウトの設定（30分）
timeout: "1800s"
