version: "3"
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bgr4_development
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.db
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: bgr4_development
      RAILS_ENV: development
      INITIALIZE_DB: "true"
    volumes:
      - .:/app
    command: ["./start.sh"]

volumes:
  postgres_data:
