apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bgr4-api-fixed
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/ingress: all
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/bgr4-project/bgr4-api-fixed:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 8080
            timeoutSeconds: 240
      serviceAccountName: bgr4-cloudrun-sa@bgr4-project.iam.gserviceaccount.com
      timeoutSeconds: 600
  traffic:
    - percent: 100
      latestRevision: true
