steps:
  # ビルドとプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bgr4-front-simple", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bgr4-front-simple"]

  # Cloud Runへのデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "bgr4-front-simple",
        "--image",
        "gcr.io/$PROJECT_ID/bgr4-front-simple",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "256Mi",
        "--min-instances",
        "0",
        "--max-instances",
        "2",
        "--port",
        "8080",
        "--set-env-vars",
        "NODE_ENV=production,NEXT_PUBLIC_API_URL=https://bgr4-api-db-349403738734.asia-northeast1.run.app",
      ]

# イメージをContainer Registryに保存
images:
  - "gcr.io/$PROJECT_ID/bgr4-front-simple"

timeout: 1800s
