name: Preview Deploy

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: bgr-v2/package-lock.json
        
    - name: Install dependencies
      run: |
        cd bgr-v2
        npm ci
        
    - name: Build for preview
      run: |
        cd bgr-v2
        npm run build
      env:
        NODE_ENV: production
        
    - name: Deploy preview to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './bgr-v2/out'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Preview deploy from PR #${{ github.event.number }}"
        alias: deploy-preview-${{ github.event.number }}
        enable-pull-request-comment: true
        enable-commit-comment: false
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}