name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'bgr-v2/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'bgr-v2/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Type check, Lint, Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bgr-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'bgr-v2/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          NEXT_PUBLIC_APP_URL: 'https://bgrq.netlify.app'
          # Supabase や他のシークレットは必要に応じてGitHub Secretsで設定
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: npm run build

